var GAME=GAME||{};GAME.GameObjectPool=function(a){this.classType=a;this.pool=[]};GAME.GameObjectPool.constructor=GAME.GameObjectPool;GAME.GameObjectPool.prototype.getObject=function(){var a=this.pool.pop();a||(a=new this.classType);return a};GAME.GameObjectPool.prototype.returnObject=function(){};Fighter=function(){Fighter.textures=[];for(var a=0;29>a;a++){var b="rollSequence00";9>a&&(b+="0");b+=a+1+".png";Fighter.textures.push(PIXI.Texture.fromFrame(b))}PIXI.Sprite.call(this,Fighter.textures[0]);this.afterburner=PIXI.Sprite.fromFrame("afterburner.png");this.addChild(this.afterburner);this.afterburner.rotation=1E-4;this.afterburner.anchor.x=0.5;this.afterburner.position.y=130;this.afterburner.position.x=1;this.afterburner.blendMode=PIXI.blendModes.SCREEN};Fighter.constructor=Fighter;
Fighter.prototype=Object.create(PIXI.Sprite.prototype);Fighter.prototype.updateTransform=function(){this.anchor.x=this.anchor.y=0;PIXI.Sprite.prototype.updateTransform.call(this);var a=29*(this.position.y/height);0>a&&(a=0);a||(a=0);a=Fighter.textures[Math.round((a+10)%28)];this.setTexture(a);a=a.realSize;this.afterburner.alpha=0.7+0.3*Math.random();this.anchor.x=-((a.x-87.5)/a.w);this.anchor.y=-((a.y-100)/a.h)};
Fighter.prototype.updateTransformOne=function(){this.anchor.x=this.anchor.y=0;PIXI.Sprite.prototype.updateTransform.call(this);var a=29*(this.position.y/height);0>a&&(a=0);a||(a=0);15<a&&(a=15);a=Fighter.textures[Math.round((a+14)%28)];this.setTexture(a);a=a.realSize;this.afterburner.alpha=0.7+0.3*Math.random();this.anchor.x=-((a.x-87.5)/a.w);this.anchor.y=-((a.y-100)/a.h)};
Fighter.prototype.updateTransformTwo=function(){this.anchor.x=this.anchor.y=0;PIXI.Sprite.prototype.updateTransform.call(this);var a=Fighter.textures[1];this.setTexture(a);a=a.realSize;this.afterburner.alpha=0.7+0.3*Math.random();this.anchor.x=-((a.x-87.5)/a.w);this.anchor.y=-((a.y-100)/a.h)};var PIXI=PIXI||{};
ScrollItem=function(a){this.data=a;this.updateTransform=function(){this.rotation!=this.rotationCache&&(this.rotationCach=this.rotation,this._sr=Math.sin(this.rotation),this._cr=Math.cos(this.rotation));this.localTransform[0]=this._cr*this.scale.x;this.localTransform[1]=-this._sr*this.scale.y;this.localTransform[3]=this._sr*this.scale.x;this.localTransform[4]=this._cr*this.scale.y;var a=Math.floor(camera.y),a=a%(this.data.length/2);this.localTransform[2]=this.data.position[2*a];this.localTransform[5]=this.data.position[2*
a+1];mat3.multiply(this.localTransform,this.parent.worldTransform,this.worldTransform);this.worldAlpha=this.alpha*this.parent.worldAlpha;for(var a=0,c=this.children.length;a<c;a++)this.children[a].updateTransform()}};Clouds=function(){PIXI.DisplayObjectContainer.call(this);this.clouds=[];this.focalLength=500;for(var a=0;20>a;a++){var b=PIXI.Sprite.fromImage("/img/cloud.png");this.clouds.push(b);this.addChild(b);b.anchor.x=b.anchor.y=0.5;b.position3D={x:2E3*Math.random()-1E3,y:150*Math.random()-75,z:-250*Math.random()};b.alpha=1}};Clouds.constructor=Clouds;Clouds.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);
Clouds.prototype.updateTransform=function(){if(this.visible){PIXI.DisplayObjectContainer.prototype.updateTransform.call(this);for(var a=0;a<this.clouds.length;a++){var b=this.clouds[a],c=this.focalLength/(this.focalLength+b.position3D.z);b.position.x=b.position3D.x*c;b.position.y=(b.position3D.y-camera.y)*c;b.position.y+=200;b.position.x+=width/2;b.scale.x=3*c;b.scale.y=2*c;b.position3D.z-=1;-130>b.position3D.z&&(c=b.position3D.z+130,c/=20,b.alpha=1-c);-150>b.position3D.z&&(b.position3D.z+=250,this.addChildAt(b,
0),b.alpha=1)}}};Conclusion=function(){PIXI.DisplayObjectContainer.call(this);this.div=document.getElementById("footer");this.copy=document.getElementById("copy");document.body.appendChild(this.div)};Conclusion.constructor=Conclusion;Conclusion.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);
Conclusion.prototype.updateTransform=function(){PIXI.DisplayObject.prototype.updateTransform.call(this);this.div.style.display=this.visible?"block":"none";var a=this.worldTransform,a="matrix("+a[0]+", "+a[3]+","+a[1]+","+a[4]+","+(a[2]-this.width/2+offset)+","+(a[5]-17*a[4])+")";this.div.style["-webkit-transform-origin"]="50% 0%";this.div.style["transform-origin"]="50% 0%";this.div.style["-webkit-transform"]=a;this.div.style.transform=a};
Conclusion.prototype.resize=function(a){1024>a&&(a=1024);this.width=a;this.div.style.width=a+"px"};PIXI=PIXI||{};
ScrollView=function(a){this.data=a;this.positionScale=new PIXI.Point(1,1);a=PIXI.Texture.fromFrame("arrowHint01.png");this.arrows=new PIXI.MovieClip([a,a,a,a,a,a,a,a,a,a,a,PIXI.Texture.fromFrame("arrowHint02.png"),PIXI.Texture.fromFrame("arrowHint03.png"),PIXI.Texture.fromFrame("arrowHint04.png")]);this.arrows.animationSpeed=0.1;this.arrows.play();a=new PIXI.DisplayObjectContainer;a.anchor=new PIXI.Point;var b=PIXI.Sprite.fromFrame("earth_BG_top.png"),c=PIXI.Sprite.fromImage("/img/earth_BG.jpg");a.addChild(b);
a.addChild(c);c.position.x=-512;c.position.y=-373;b.position.x=-512;b.position.y=-406;this.footerContainer=new PIXI.DisplayObjectContainer;this.nebulae=new PIXI.DisplayObjectContainer;this.nebulae.nebulaeInner=PIXI.Sprite.fromFrame("nebulae.png");this.nebulae.innerInner=new PIXI.DisplayObjectContainer;this.nebulae.nebulaeInner.anchor.x=0.5;this.nebulae.nebulaeInner.anchor.y=0.5;this.nebulae.innerInner.scale.y=1;this.nebulae.innerInner.scale.x=3;this.nebulae.addChild(this.nebulae.innerInner);this.nebulae.innerInner.addChild(this.nebulae.nebulaeInner);
this.nebulae.anchor=new PIXI.Point;this.nebulae.nebulaeInner.blendMode=PIXI.blendModes.SCREEN;this.playHTML=new PlayButton("html/",!0);this.playFlash=new PlayButton("flash/");this.playIOS=new IOSButton("flash/");this.alienSwarm=new AlienSwarm;this.heartFlash=new PIXI.DisplayObjectContainer;var b=new PIXI.Sprite.fromImage("/img/flashWedge.png"),c=new PIXI.Sprite.fromImage("/img/flashBanner.png"),d=new PIXI.Sprite.fromFrame("weHeartFlash.png");b.anchor.x=1;c.position.x=-49;c.position.y=49;c.anchor.x=
1;c.scale.x=20;d.position.x=-434;d.position.y=60;this.heartFlash.banner=c;this.heartFlash.addChild(b);this.heartFlash.addChild(c);this.heartFlash.addChild(d);this.heartFlash.position.x=300;this.heartFlash.position.y=100;this.heartHTML=new PIXI.DisplayObjectContainer;b=new PIXI.Sprite.fromImage("/img/htmlWedge.png");c=new PIXI.Sprite.fromImage("/img/htmlBanner.png");d=new PIXI.Sprite.fromFrame("weHeartHTML.png");c.position.x=49;c.position.y=49;c.anchor.x=0;c.scale.x=20;d.position.x=58;d.position.y=60;
this.heartHTML.banner=c;this.heartHTML.addChild(b);this.heartHTML.addChild(c);this.heartHTML.addChild(d);this.heartHTML.position.x=300;this.heartHTML.position.y=100;this.conclusion=new Conclusion;var b={space:"/img/space_BG.jpg",intro1:"introCopy_01.png",intro2:"introCopy_02.png",intro3:"introCopy_03.png",intro4:"introCopy_04.png",intro5:"introCopy_05.png",pentBlur01:"pentBlur01.png",pentBlur02:"pentBlur02.png",pentBlur03:"pentBlur03.png",pentBlur04:"pentBlur04.png",arrowHint01:"arrows",moon:"moon.png",
rainbowFlare:"rainbowFlareFLAT.png",titleFlash:"titleFlash.png",titleHTML:"titleHTML.png",VS:"VS.png",CTA_scroll:"CTA_scroll.png",alienCurve:"swarm",nebulae:"nebulae",horizon:"horizon.png",whiteline:"/img/whiteline.png",flaredisc:"flareDisc.png",mainFlare:"mainFlare.png",flashDisc_Col:"flashDisc_Col.png",flashDisc_W:"flashDisc_W.png",htmlDisc_Col:"htmlDisc_Col.png",htmlDisc_W:"htmlDisc_W.png",screen01:"screeny_01.png",screen02:"screeny_02.png",screen03:"screeny_03.png",mobileIcon:"mobileIcon.png",
desktopIcon:"desktopIcon.png",appDownload:"appDownload.png",chooseVersion:"invadersChoose.png",playButton:"play",VS_small:"VS_small.png",USBhead:"USB_head.png",cloudFade:"/img/cloudFade.png",cloud01:"cloud_01.png",cloud02:"cloud_02.png",cloud03:"cloud_03.png",cloud04:"cloud_04.png",cloud05:"cloud_05.png",cloud06:"cloud_06.png",alien:"alien",alienSmall:"alien",sun:"sun.png",earth:"earth",afterburner:"afterburner.png",jet:"fighter",inconclusion:"/img/inconclusion.png",heartFlash:"heartFlash",heartHTML:"heartHTML",
richochet:"/img/richochet.png",basePanel:"basePanel",ground:"/img/groundLevel.jpg"},c={space:ScrollView.SCALE_FIT,rainbowFlare:ScrollView.SCALE_FIT_PRESERVE,alienSmall:ScrollView.SCALE_NONE,moon:ScrollView.SCALE_POSITION_Y,nebulae:ScrollView.SCALE_FIT_PRESERVE,horizon:ScrollView.SCALE_FIT,heartFlash:ScrollView.FOOTER,heartHTML:ScrollView.FOOTER,VS:ScrollView.SCALE_POSITION_Y,CTA_scroll:ScrollView.SCALE_NONE,arrowHint01:ScrollView.SCALE_POSITION_Y,flaredisc:ScrollView.SCALE_FIT_PRESERVE,mainFlare:ScrollView.SCALE_FIT_PRESERVE,
cloud01:ScrollView.SCALE_FIT_PRESERVE,cloud02:ScrollView.SCALE_FIT_PRESERVE,cloud03:ScrollView.SCALE_FIT_PRESERVE,cloud04:ScrollView.SCALE_FIT_PRESERVE,cloud05:ScrollView.SCALE_FIT_PRESERVE,cloud06:ScrollView.SCALE_FIT_PRESERVE,cloudFade:ScrollView.SCALE_FIT,sun:ScrollView.SCALE_FIT_PRESERVE,mainFlare:ScrollView.SCALE_FIT_PRESERVE,earth:ScrollView.SCALE_FIT,afterburner:ScrollView.SCALE_FIT_PRESERVE,jet:ScrollView.SCALE_POSITION_Y,alien:ScrollView.SCALE_POSITION_Y,ground:ScrollView.SCALE_FIT,inconclusion:ScrollView.FOOTER,
richochet:ScrollView.FOOTER,basePanel:ScrollView.FOOTER,blackBase:ScrollView.FOOTER,pentBlur01:ScrollView.SCALE_POSITION,pentBlur02:ScrollView.SCALE_POSITION,pentBlur03:ScrollView.SCALE_POSITION,pentBlur04:ScrollView.SCALE_POSITION},e=d=0,h=0,g;for(g in this.data){this.data[g].resize=c[this.data[g].view];this.data[g].resize||(this.data[g].resize=ScrollView.SCALE_NONE);this.data[g].positionScale=new PIXI.Point(1,1);this.data[g].sizeScale=new PIXI.Point(1,1);var f,j=b[this.data[g].view];if(j)if("earth"==
j)f=a;else if("alien"==j)f=new Alien,6>e&&(this.data[g].resize=ScrollView.SCALE_NONE),e++;else if("fighter"==j)f=new Fighter,0==d&&(f.updateTransform=f.updateTransformOne,this.data[g].resize=ScrollView.SCALE_NONE),3==d&&(f.updateTransform=f.updateTransformTwo,this.data[g].resize=ScrollView.FOOTER),d++;else if("nebulae"==j)f=this.nebulae;else if("heartFlash"==j)f=this.heartFlash,f.anchor=new PIXI.Point;else if("heartHTML"==j)f=this.heartHTML,f.anchor=new PIXI.Point;else if("basePanel"==j)f=this.conclusion,
f.anchor=new PIXI.Point;else if("swarm"==j)f=this.alienSwarm,f.anchor=new PIXI.Point;else if("appDownload.png"==j)f=this.playIOS;else if("arrows"==j)f=this.arrows;else if("play"==j)f=0==h?this.playFlash:this.playHTML,h++;else try{f=PIXI.Sprite.fromFrame(j)}catch(k){f=PIXI.Sprite.fromImage(j)}else f=PIXI.Sprite.fromImage("sun.png"),console.log("could'nt find "+this.data[g].view);f.anchor.x=f.anchor.y=0.5;this.data[g].sprite=f;f.visible=!1;this.data[g].resize==ScrollView.FOOTER?this.footerContainer.addChild(f):
stage.addChild(f)}stage.addChild(this.footerContainer);HIGH&&(this.rain=new Rain,stage.addChild(this.rain),this.miniClouds=new MiniClouds,this.showCache=!1)};ScrollView.constructor=ScrollView;
ScrollView.prototype.updatePosition=function(a){0>a&&(a=0);703<a&&(a=703);if(HIGH){this.rain.mode=480<a&&517>a?0:1;this.rain.update();var b=495<a;this.showCache!=b&&((this.showCache=b)?stage.addChildAt(this.miniClouds,8):stage.removeChild(this.miniClouds));b&&this.miniClouds.update()}this.nebulae.nebulaeInner.rotation+=0.0010;for(var c in this.data)if(b=this.data[c],a>=b.startFrame&&a<b.endFrame-1){b.sprite.visible=!0;var d=a-b.startFrame,e=Math.floor(d),h=Math.ceil(d),g=d-e,f=b.position[2*e],f=f+
(b.position[2*h]-f)*g,j=b.position[2*e+1],j=j+(b.position[2*h+1]-j)*g;Math.round(d);b.resize==ScrollView.FOOTER?(b.sprite.position.x=f,b.sprite.position.y=j):(b.sprite.position.x=f*b.positionScale.x+width/2,b.sprite.position.y=j*b.positionScale.y+height/2);f=d=1;b.scale&&(d=b.scale[2*e],d+=(b.scale[2*h]-d)*g,f=b.scale[2*e+1],f+=(b.scale[2*h+1]-f)*g);b.sprite.scale.x=d*b.sizeScale.x;b.sprite.scale.y=f*b.sizeScale.y;d=1;b.alpha&&(d=b.alpha[e],d+=(b.alpha[h]-d)*g);b.sprite.alpha=d;b.rotation&&(e=b.rotation[e],
interRotation=e+(b.rotation[h]-e)*g,b.sprite.rotation=interRotation*(Math.PI/180))}else b.sprite.visible=!1};ScrollView.SCALE_NONE=0;ScrollView.SCALE_FIT=1;ScrollView.SCALE_FIT_PRESERVE=2;ScrollView.SCALE_X=3;ScrollView.SCALE_Y=4;ScrollView.SCALE_POSITION=5;ScrollView.SCALE_POSITION_Y=6;ScrollView.FOOTER=7;ScrollView.SCALE_POSITION_REAL=8;
ScrollView.prototype.resize=function(a,b){this.w=a;this.h=b;this.positionScale.x=a/1024;this.positionScale.y=b/768;var c=a/1024>b/768?b/768:a/1024;1<c&&(c=1);for(var d in this.data){var e=this.data[d];e.resize==ScrollView.SCALE_FIT?(e.sizeScale=this.positionScale,e.positionScale=this.positionScale):e.resize==ScrollView.SCALE_FIT_PRESERVE?(e.sizeScale.x=e.sizeScale.y=this.positionScale.y,e.positionScale=this.positionScale):e.resize==ScrollView.SCALE_X?(e.sizeScale.x=this.positionScale.x,e.positionScale=
this.positionScale):e.resize==ScrollView.SCALE_Y?(e.sizeScale.y=this.positionScale.y,e.positionScale=this.positionScale):e.resize==ScrollView.SCALE_POSITION?e.sizeScale.y=e.sizeScale.x=1>this.positionScale.y?this.positionScale.y:1:e.resize==ScrollView.SCALE_POSITION_REAL?(e.positionScale.x=this.positionScale.x,e.positionScale.y=this.positionScale.y):e.resize==ScrollView.SCALE_POSITION_Y?(e.positionScale.y=this.positionScale.y,e.positionScale.x=c,e.sizeScale.y=e.sizeScale.x=c):e.resize==ScrollView.SCALE_NONE&&
(e.sizeScale.y=e.sizeScale.x=c,e.positionScale.x=e.positionScale.y=c)}this.footerContainer.scale.x=this.footerContainer.scale.y=c;this.footerContainer.position.y=height-364*c;this.footerContainer.position.x=a/2;offset=width/2-a/2;this.conclusion.resize(a/c,b);c=a/c;1024>c&&(c=1024);this.heartFlash.banner.scale.x=c/2/26;this.heartHTML.banner.scale.x=c/2/26};PIXI=PIXI||{};
RocketView=function(){this.rockets=rockets.rockets;this.dust=rockets.dust;this.positionScale=new PIXI.Point(1,1);this.rocketView=new PIXI.DisplayObjectContainer;stage.addChildAt(this.rocketView,20);var a=["missileCloud01.png","missileCloud02.png","missileCloud03.png"],b=0,c;for(c in this.rockets){var d=PIXI.Sprite.fromFrame("phoenix.png");d.anchor.x=d.anchor.y=0.5;d.fire=PIXI.Sprite.fromFrame("phoenixPlume.png");d.addChild(d.fire);d.fire.anchor.x=0.5;d.fire.position.y=30;d.fire.rotation=1E-4;d.anchor.y=
0.6;this.rockets[c].sprite=d;this.rockets[c].positionScale=new PIXI.Point(1,1);this.rocketView.addChild(d)}this.rockets[c].sprite.id="rocket";for(c in this.dust)d=PIXI.Sprite.fromFrame(a[b%3]),b++,d.anchor.x=d.anchor.y=0.5,this.dust[c].sprite=d,this.dust[c].random=2*Math.random()*Math.PI,this.dust[c].randomSign=Math2.randomPlusMinus(),this.dust[c].positionScale=new PIXI.Point(1,1),this.dust[c].position[3]=0,this.rocketView.addChild(d)};RocketView.constructor=ScrollView;
RocketView.prototype.updatePosition=function(a){a=3*(a-277);if(0>a||100<a)this.rocketView.visible=!1;else{this.rocketView.visible=!0;0>a&&(a=0);390<a&&(a=390);for(var b in this.rockets){var c=this.rockets[b];c.sprite.fire.alpha=0.7+0.3*Math.random();if(a>=c.startFrame&&a<c.endFrame){c.sprite.visible=!0;var d=a-c.startFrame-1,e=Math.floor(d),h=Math.ceil(d),g=d-e,f=c.position[3*e],j=c.position[3*h],f=f+(j-f)*g,j=c.position[3*e+1],k=c.position[3*h+1],j=j+(k-j)*g;Math.round(d);c.sprite.position.x=f*this.positionScale.x+
width/2;c.sprite.position.y=(j+150)*this.positionScale.y+height/2;c.sprite.scale.x=c.sprite.scale.y=0.7*this.sizeScale;d=c.position[3*e+2];f=c.position[3*h+2];d+=(f-d)*g;c.sprite.rotation=Math.PI-d}else c.sprite.visible=!1}for(b in this.dust)c=this.dust[b],a>=c.startFrame&&a<c.endFrame?(c.sprite.visible=!0,c.sprite.alpha=1,d=a-c.startFrame,e=Math.floor(d),h=Math.ceil(d),g=d-e,f=c.position[5*e],j=c.position[5*h],f+=(j-f)*g,j=c.position[5*e+1],k=c.position[5*h+1],j+=(k-j)*g,Math.round(d),c.sprite.position.x=
f*this.positionScale.x+width/2,c.sprite.position.y=(j+150)*this.positionScale.y+height/2,d=c.position[5*e+2],f=c.position[5*h+2],d+=(f-d)*g,c.sprite.rotation=2*(d*(Math.PI/180)+c.random)*c.randomSign,d=c.position[5*e+3],c.sprite.scale.x=c.sprite.scale.y=4*(d+(c.position[5*h+3]-d)*g)*this.sizeScale,e=c.position[5*e+4],c.sprite.alpha=e+(c.position[5*h+4]-e)*g):c.sprite.visible=!1}};
RocketView.prototype.resize=function(a,b){this.positionScale.x=a/1024;this.positionScale.y=b/768;this.sizeScale=b/768;1<this.sizeScale&&(this.sizeScale=1);1<this.positionScale.x&&(this.positionScale.x=1);1<this.positionScale.y&&(this.positionScale.y=1);for(var c in this.data){var d=this.data[c];d.resize&&(d.positionScale=this.positionScale)}};PIXI=PIXI||{};ScaleView=function(a){this.data=a;this.positionScale=new PIXI.Point(1,1);a={};for(var b in this.data){var c;c=(c=this.data[b].view)?PIXI.Sprite.fromFrame(c+".png"):PIXI.Sprite.fromImage("/img/smoke.png");c.anchor.x=c.anchor.y=0.5;this.data[b].sprite=c;this.data[b].resize=a[this.data[b].view];this.data[b].positionScale=new PIXI.Point(1,1);stage.addChild(c)}};ScaleView.constructor=ScaleView;
ScaleView.prototype.updatePosition=function(a){0>a&&(a=0);455<a&&(a=455);for(var b in this.data){var c=this.data[b];if(a>=c.startFrame&&a<c.endFrame-1){c.sprite.visible=!0;var d=a-c.startFrame,e=Math.floor(d),h=Math.ceil(d),g=d-e,f=c.position[2*e],f=f+(c.position[2*h]-f)*g,j=c.position[2*e+1],j=j+(c.position[2*h+1]-j)*g;Math.round(d);c.sprite.position.x=f*this.positionScale.x+width/2;c.sprite.position.y=j*this.positionScale.y+height/2;f=d=1;c.scale&&(d=c.scale[2*e],d+=(c.scale[2*h]-d)*g,f=c.scale[2*
e+1],f+=(c.scale[2*h+1]-f)*g);c.sprite.scale.x=d*c.positionScale.x;c.sprite.scale.y=f*c.positionScale.y;d=1;c.alpha&&(d=c.alpha[e],d+=(c.alpha[h]-d)*g);c.sprite.alpha=d;d=0;c.rotation&&(e=c.rotation[e],d=e+(c.rotation[h]-e)*g);c.sprite.rotation=d*(Math.PI/180)}else c.sprite.visible=!1}};
ScaleView.prototype.resize=function(a){a=0.9*(a/1024);1<a&&(a=1);this.positionScale.x=this.positionScale.y=a;for(var b in this.data)a=this.data[b],a.positionScale=this.positionScale,a.resize!=ScrollView.SCALE_FIT&&(a.resize==ScrollView.SCALE_FIT_PRESERVE?a.positionScale.x=a.positionScale.y=this.positionScale.y:a.resize==ScrollView.SCALE_X?a.positionScale.x=this.positionScale.x:a.resize==ScrollView.SCALE_Y&&(a.positionScale.y=this.positionScale.y))};Menu=function(){PIXI.DisplayObjectContainer.call(this);this.bg=PIXI.Sprite.fromFrame("navFade.png");this.bg.position.x=-160;this.addChild(this.bg);this.blackStrip=PIXI.Sprite.fromFrame("BGslit.png");this.blackStrip.anchor.x=0.5;this.addChild(this.blackStrip);this.button1=new PIXI.Button("nav_homeW.png","nav_homeG.png");this.button2=new PIXI.Button("nav_playW.png","nav_playG.png");this.button3=new PIXI.Button("nav_findW.png","nav_findG.png");this.button4=new PIXI.Button("nav_concW.png","nav_concG.png");
this.button1.id=0;this.button2.id=1;this.button3.id=2;this.button4.id=3;this.addChild(this.button1);this.addChild(this.button2);this.addChild(this.button3);this.addChild(this.button4);this.button1.position.x=0;this.button2.position.x=112;this.button3.position.x=211;this.button4.position.x=345;this.currentButton=this.button1;this.button1.select();var a=this;this.button1.onClicked=function(){a.selectButton(this,!0)};this.button1.onClicked=function(){a.selectButton(this,!0)};this.button2.onClicked=function(){a.selectButton(this,
!0)};this.button3.onClicked=function(){a.selectButton(this,!0)};this.button4.onClicked=function(){a.selectButton(this,!0)};this.progressBar=PIXI.Sprite.fromImage("/img/progressBar.png");this.progressBar.position.x=37;this.addChild(this.progressBar);for(var b=[-213.5,-110.5,6.5,160.5],c=0;c<b.length;c++){var d=PIXI.Sprite.fromFrame("navArrow.png");this.addChild(d);d.anchor.x=0.5;d.anchor.y=0.5;d.position.x=b[c]+213.5+37;d.position.y=4}};Menu.constructor=Menu;Menu.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);
Menu.prototype.selectById=function(a){0==a?this.selectButton(this.button1):1==a?this.selectButton(this.button2):2==a?this.selectButton(this.button3):3==a&&this.selectButton(this.button4)};Menu.prototype.selectButton=function(a,b){if(this.currentButton!=a&&(this.currentButton.deselect(),this.currentButton=a,this.currentButton.select(),b))this.onMenuPressed(a.id)};
Menu.prototype.updateProgress=function(a){for(var b=0,c=0;c<position.length;c++)a>position[c]&&(b=c);a=(a-position[b])/(position[b+1]-position[b])*(positionReal[b+1]-positionReal[b]);this.progressBar.scale.x=3>b?(positionReal[b]+a)/660:1};var positionReal=[0,181,387,649],position=[0,386,553,649];Menu.prototype.resize=function(a){this.blackStrip.width=1.5*a;this.position.x=a/2-240};PlayButton=function(a,b){this.url=a;this.anchor=new PIXI.Point;PIXI.DisplayObjectContainer.call(this);this.div=document.createElement("div");this.div.style.position="fixed";this.div.style.cursor="pointer";this.div.style.background="#FF0000";this.div.style.opacity=0;document.body.appendChild(this.div);this.tint=PIXI.Sprite.fromFrame("navTint.png");b?(this.white=PIXI.Texture.fromFrame("playButtonHTML.png"),this.yellow=PIXI.Texture.fromFrame("playButtonHTMLRoll.png")):(this.white=PIXI.Texture.fromFrame("playButtonFlash.png"),
this.yellow=PIXI.Texture.fromFrame("playButtonFlashRoll.png"));this.sprite=new PIXI.Sprite(this.white);this.sprite.anchor.x=0.5;this.sprite.anchor.y=0.5;this.tint.width=this.sprite.width+20;this.tint.position.y=-50;this.width=this.tint.width;this.height=this.tint.height;this.addChild(this.sprite);$(this.div).mouseover($.proxy(this.onMouseOver,this));$(this.div).mouseout($.proxy(this.onMouseOut,this));$(this.div).click($.proxy(this.onMouseClick,this));this.tl=new TimelineLite;this.tl.call(this.onReachTop.bind(this));
this.tl.to(this.sprite.scale,0.1,{x:1.2,y:1.2,ease:Sine.easeOut});this.tl.stop()};PlayButton.constructor=PlayButton;PlayButton.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);PlayButton.prototype.select=function(){this.over=this.selected=!0;this.tl.play()};PlayButton.prototype.deselect=function(){this.selected=!1;this.tl.reverse();this.over=!1};PlayButton.prototype.onMouseClick=function(){HIGH?window.open(this.url):window.open(this.url,"_self")};
PlayButton.prototype.onMouseOver=function(){this.selected||(this.tl.play(),this.over=!0)};PlayButton.prototype.onReachTop=function(){this.over?this.sprite.setTexture(this.yellow):this.sprite.setTexture(this.white)};PlayButton.prototype.onMouseOut=function(){this.selected||(this.tl.reverse(),this.over=!1)};
PlayButton.prototype.updateTransform=function(){PIXI.DisplayObjectContainer.prototype.updateTransform.call(this);this.div.style.display=this.visible?"block":"none";this.div.style.width="187px";this.div.style.height="98px";var a=this.worldTransform,a="matrix("+a[0]+", "+a[3]+","+a[1]+","+a[4]+","+(a[2]-93.5+offset)+","+(a[5]-49)+")";this.div.style["-webkit-transform"]=a;this.div.style.transform=a};PIXI.Button=function(a,b){PIXI.DisplayObjectContainer.call(this);this.div=document.createElement("div");this.div.style.position="fixed";this.div.style.cursor="pointer";this.div.style.background="#FF0000";this.div.style.opacity=0;document.body.appendChild(this.div);this.tint=PIXI.Sprite.fromFrame("navTint.png");this.addChild(this.tint);this.white=PIXI.Texture.fromFrame(a);this.yellow=PIXI.Texture.fromFrame(b);this.sprite=new PIXI.Sprite(this.white);this.sprite.position.y=15;this.sprite.position.x=
10;this.tint.width=this.sprite.width+20;this.tint.position.y=-50;this.width=this.tint.width;this.height=this.tint.height;this.addChild(this.sprite);$(this.div).mouseover($.proxy(this.onMouseOver,this));$(this.div).mouseout($.proxy(this.onMouseOut,this));$(this.div).click($.proxy(this.onMouseClick,this));this.tl=new TimelineLite;this.tl.to(this.sprite.position,0.075,{y:-20,ease:Sine.easeIn});this.tl.to(this.tint.position,0.075,{y:-9,ease:Sine.easeOut});this.tl.call(this.onReachTop.bind(this));this.tl.to(this.sprite.position,
0.075,{y:15,ease:Sine.easeOut});this.tl.stop()};PIXI.Button.constructor=Conclusion;PIXI.Button.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);PIXI.Button.prototype.select=function(){this.over=this.selected=!0;this.tl.play()};PIXI.Button.prototype.deselect=function(){this.selected=!1;this.tl.reverse();this.over=!1};PIXI.Button.prototype.onMouseClick=function(){this.onClicked()};PIXI.Button.prototype.onMouseOver=function(){this.selected||(this.tl.play(),this.over=!0)};
PIXI.Button.prototype.onReachTop=function(){this.over?this.sprite.setTexture(this.yellow):this.sprite.setTexture(this.white)};PIXI.Button.prototype.onMouseOut=function(){this.selected||(this.tl.reverse(),this.over=!1)};
PIXI.Button.prototype.updateTransform=function(){PIXI.DisplayObjectContainer.prototype.updateTransform.call(this);this.div.style.display=this.visible?"block":"none";this.div.style.width=this.width+"px";this.div.style.height=this.height+"px";var a=this.worldTransform,a="matrix("+a[0]+", "+a[3]+","+a[1]+","+a[4]+","+(a[2]+offset)+","+a[5]+")";this.div.style["-webkit-transform"]=a;this.div.style.transform=a};Alien=function(){Alien.textures=[];for(var a=0;20>a;a++){var b="alienAnim_",c=a;9>=c&&(b+="0");b+=c+".png";Alien.textures.push(PIXI.Texture.fromFrame(b))}this.framy=0;PIXI.Sprite.call(this,Alien.textures[0])};Alien.constructor=Alien;Alien.prototype=Object.create(PIXI.Sprite.prototype);Alien.prototype.updateTransform=function(){this.anchor.x=this.anchor.y=0;PIXI.Sprite.prototype.updateTransform.call(this);var a=this.framy+=0.2;0>a&&(a=0);a||(a=0);a=Alien.textures[Math.round(a%19)];this.setTexture(a)};
Alien.prototype.updateTransformOne=function(){this.anchor.x=this.anchor.y=0;PIXI.Sprite.prototype.updateTransform.call(this);var a=29*(this.position.y/height);0>a&&(a=0);a||(a=0);15<a&&(a=15);a=Fighter.textures[Math.round((a+14)%28)];this.setTexture(a);a=a.realSize;this.anchor.x=-((a.x-87.5)/a.w);this.anchor.y=-((a.y-100)/a.h)};
Alien.prototype.updateTransformTwo=function(){this.anchor.x=this.anchor.y=0;PIXI.Sprite.prototype.updateTransform.call(this);var a=Fighter.textures[1];this.setTexture(a);a=a.realSize;this.anchor.x=-((a.x-87.5)/a.w);this.anchor.y=-((a.y-100)/a.h)};PixiDust=function(){PIXI.DisplayObjectContainer.call(this);this.particals=[];this.max=HIGH?50:5;for(var a=this.count=0;a<this.max;a++){var b=new ParticalDust;b.home.y=Math.random()*-height;b.position.x=b.home.x=110640*Math.random();b.speed=new PIXI.Point(0.1*(Math.random()-0.5),0.2*(Math.random()-1));this.particals.push(b);this.addChild(b)}this.focalLength=150};PixiDust.constructor=PixiDust;PixiDust.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);
PixiDust.prototype.update=function(){for(var a=0;a<this.particals.length;a++){var b=this.particals[a],c=this.focalLength/(this.focalLength+b.z);b.scale.x=b.scale.y=1*c;b.position.x+=b.speed.x;b.home.y+=b.speed.y;b.position.y=1.5*(b.home.y-10*camera.y)*c;b.position.y%=height;0>b.position.y&&(b.position.y+=height);b.position.x%=width;0>b.position.x&&(b.position.x+=width);b.rotation+=b.rotationSpeed}};
PixiDust.prototype.resize=function(){for(var a=0;a<this.particals.length;a++){var b=this.particals[a];b.position.x=b.home.x=110640*Math.random()}};
ParticalDust=function(){ParticalDust.debrieCount++;ParticalDust.globalCount++;ParticalDust.debrieCount=0;PIXI.Sprite.call(this,PIXI.Texture.fromFrame(ParticalDust.frames[ParticalDust.globalCount%4]));this.anchor.x=0.5;this.anchor.y=0.5;this.z=500*Math.random();this.rotation=2*Math.random()*Math.PI;this.rotationSpeed=0.01*(Math.random()-0.5);this.home=new PIXI.Point;this.alpha=0.5+0.5*Math.random()};ParticalDust.globalCount=0;ParticalDust.debrieCount=0;
ParticalDust.framesRocks=["rock01.png","rock02.png","rock03.png","rock04.png","beam.png"];ParticalDust.frames=["spacedust.png","spacedust.png","spacedust.png","spacedust.png"];ParticalDust.constructor=ParticalDust;ParticalDust.prototype=Object.create(PIXI.Sprite.prototype);AlienSwarm=function(){PIXI.DisplayObjectContainer.call(this);this.pool=new GAME.GameObjectPool(MiniAlien);this.aliens=[];this.count=0;this.focalLength=300};
AlienSwarm.data=[546.7,73.9,-89.21058654785156,537.7,73.2,-90.30949401855469,526.9,72.45,-92.0457763671875,514.4,72,-94.03938293457031,500.15,71.85,-96.29374694824219,484.05,72.5,-98.8055419921875,466.15,73.85,-101.76046752929688,446.75,76.45,-104.57228088378906,425.85,80.6,-107.06285095214844,403.35,86,-109.7996826171875,379.4,93,-112.77784729003906,354.25,101.75,-115.80471801757812,328.3,113.15,-117.82106018066406,301.35,126.5,-118.09934997558594,272.9,140.8,-118.57345581054688,242.95,155.9,-119.05201721191406,
212,173,-117.57157897949219,179.1,190,-115.55903625488281,143.95,206.55,-113.33518981933594,106.5,222.3,-111.31788635253906,66.9,237.15,-109.30671691894531,25.05,250.95,-107.27114868164062,-18.95,263.8,-105.0250244140625,-65.1,275.35,-102.56999206542969,-113.3,285.5,-99.53318786621094,-163.9,293.2,-96.04573059082031,-216.5,297.25,-93.25749206542969,-271.05,298.25,-91.54270935058594,-327.4,297.6,-89.95454406738281,-385.35,296.35,-85.22276306152344,-444.8,289.4,-81.22264099121094,-505.2,277.8,-77.74102783203125,
-567.8,261.5,-73.7298583984375,-630.3,238.55,-72.64358520507812,559.3,75.5,-87.13829040527344];AlienSwarm.constructor=AlienSwarm;AlienSwarm.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);
AlienSwarm.prototype.updateTransform=function(){if(this.visible){PIXI.DisplayObjectContainer.prototype.updateTransform.call(this);this.count++;if(5<this.count&&408>camera.y&&900<height){this.count=0;var a=this.pool.getObject();this.addChild(a);this.aliens.push(a);a.scale.x=a.scale.y=1;a.position.x=width;a.count=0}var b=AlienSwarm.data.length/3-2,c=width/1024;this.position.x=width/2;for(var d=0;d<this.aliens.length;d++){a=this.aliens[d];a.count+=a.speed;var e=b*a.count,h=Math.floor(e),g=Math.ceil(e),
e=e-h,f=AlienSwarm.data[3*h],f=f+(AlienSwarm.data[3*g]-f)*e,j=AlienSwarm.data[3*h+2];interRotation=j+(AlienSwarm.data[3*g+2]-j)*e;h=AlienSwarm.data[3*h+1];g=h+(AlienSwarm.data[3*g+1]-h)*e;a.scale.x=a.scale.y=this.focalLength/(this.focalLength+a.z)*(0.1+2*a.count);a.position.x=(f+a.offset)*c;a.position.y=g+a.offset;a.rotation=interRotation*(Math.PI/180)+Math.PI/2;1<=a.count&&(this.removeChild(a),this.aliens.splice(d,1),this.pool.returnObject(a))}}};
AlienSwarm.prototype.resize=function(a){this.width=a;this.div.style.width=a+"px"};MiniAlien=function(){PIXI.Sprite.call(this,PIXI.Texture.fromFrame("alienSwarm_top.png"));this.anchor.x=0.5;this.anchor.y=0.9;this.home=new PIXI.Point(0,30*Math.random());this.speed=0.0070+0.0010*Math.random();this.rotation=Math.PI/2;this.power=100*Math.random();this.freq=0.03*Math.random();this.offset=100*Math.random();this.z=200*Math.random();this.count=0};MiniAlien.constructor=MiniAlien;MiniAlien.prototype=Object.create(PIXI.Sprite.prototype);Rain=function(){PIXI.DisplayObjectContainer.call(this);this.pool=new GAME.GameObjectPool(ParticalRain);this.particals=[];this.count=this.mode=0};Rain.constructor=Rain;Rain.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);
Rain.prototype.update=function(){if(0==this.mode){this.count+=1;for(var a=0;5>a&&!(100<this.particals.length);a++){this.count=0;var b=this.pool.getObject();this.particals.push(b);this.addChild(b);b.alpha=0.5;b.life=20+50*Math.random();b.position.x=Math.random()*width;b.position.y=Math.random()*height}}else if(1==this.mode)for(a=0;a<this.particals.length;a++)b=this.particals[a],b.life--,50>b.life&&(b.alpha=0.5*(b.life/50),0>=b.life&&(this.pool.returnObject(b),this.removeChild(b),this.particals.splice(a,
1),a--))};Rain.prototype.resize=function(){for(var a=0;a<this.particals.length;a++){var b=this.particals[a];b.position.x=b.home.x=110640*Math.random()}};ParticalRain=function(){PIXI.Sprite.call(this,PIXI.Texture.fromFrame(ParticalRain.frames[ParticalRain.globalCount%4]));ParticalRain.globalCount++;this.anchor.x=0.5;this.anchor.y=0.5};ParticalRain.globalCount=0;ParticalRain.frames=["dropplet_01.png","dropplet_02.png","dropplet_03.png","dropplet_04.png"];ParticalRain.constructor=ParticalRain;
ParticalRain.prototype=Object.create(PIXI.Sprite.prototype);MiniClouds=function(){PIXI.DisplayObjectContainer.call(this);this.particals=[];this.max=HIGH?10:5;this.count=0;this.shadow=new PIXI.DisplayObjectContainer;this.addChild(this.shadow);for(var a=0;a<this.max;a++){var b=new MiniCloud;b.home.y=Math.random()*height-height/2;b.home.x=Math.random()*width-width/2;b.speed=new PIXI.Point(1*Math.random(),0);this.particals.push(b);this.addChild(b);this.shadow.addChild(b.shadow)}this.focalLength=300};MiniClouds.constructor=MiniClouds;MiniClouds.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);
MiniClouds.prototype.update=function(){for(var a=this.focalLength/(this.focalLength+220),b=0;b<this.particals.length;b++){var c=this.particals[b],d=this.focalLength/(this.focalLength+c.z);c.scale.x=c.scale.y=1*d;c.shadow.scale.x=c.shadow.scale.y=1.5*a;c.home.x+=c.speed.x;c.home.y+=c.speed.y;var e=height/a+200,h=c.home.y-camera.y+e/2,h=h%e;0>h&&(h+=e);var h=h-e/2,e=width/a+200,g=c.home.x+e/2,g=g%e;0>g&&(g+=e);g-=e/2;c.position.x=g*d+width/2;c.position.y=h*d+height/2;c.shadow.position.x=g*a+width/2;
c.shadow.position.y=h*a+height/2}};MiniClouds.prototype.resize=function(){for(var a=0;a<this.particals.length;a++){var b=this.particals[a];b.position.x=b.home.x=110640*Math.random()}};
MiniCloud=function(){MiniCloud.globalCount++;PIXI.Sprite.call(this,PIXI.Texture.fromFrame(MiniCloud.frames[MiniCloud.globalCount%3]));this.anchor.x=0.5;this.anchor.y=0.5;this.z=100*Math.random();this.rotation=2*Math.random()*Math.PI;this.home=new PIXI.Point;this.shadow=PIXI.Sprite.fromFrame(MiniCloud.framesShadow[MiniCloud.globalCount%3]);this.shadow.anchor.x=0.5;this.shadow.anchor.y=0.5;this.shadow.alpha=0.5;this.shadow.rotation=this.rotation};MiniCloud.globalCount=0;
MiniCloud.frames=["cloud_01.png","cloud_05.png","cloud_06.png"];MiniCloud.framesShadow=["cloud1_shadow.png","cloud5_shadow.png","cloud6_shadow.png"];MiniCloud.constructor=MiniCloud;MiniCloud.prototype=Object.create(PIXI.Sprite.prototype);IOSButton=function(){this.url="https://itunes.apple.com/gb/app/waste-invaders/id501646532?mt\x3d8";this.anchor=new PIXI.Point;PIXI.DisplayObjectContainer.call(this);this.div=document.createElement("div");this.div.style.position="fixed";this.div.style.cursor="pointer";this.div.style.background="#FF0000";this.div.style.opacity=0;document.body.appendChild(this.div);this.tint=PIXI.Sprite.fromFrame("navTint.png");this.white=PIXI.Texture.fromFrame("appDownload.png");this.yellow=PIXI.Texture.fromFrame("appDownloadROLL.png");
this.sprite=new PIXI.Sprite(this.white);this.sprite.anchor.x=0.5;this.sprite.anchor.y=0.5;this.tint.width=this.sprite.width+20;this.tint.position.y=-50;this.width=this.tint.width;this.height=this.tint.height;this.addChild(this.sprite);$(this.div).mouseover($.proxy(this.onMouseOver,this));$(this.div).mouseout($.proxy(this.onMouseOut,this));$(this.div).click($.proxy(this.onMouseClick,this));this.tl=new TimelineLite;this.tl.call(this.onReachTop.bind(this));this.tl.to(this.sprite.scale,0.1,{x:1.2,y:1.2,
ease:Sine.easeOut});this.tl.stop()};IOSButton.constructor=IOSButton;IOSButton.prototype=Object.create(PIXI.DisplayObjectContainer.prototype);IOSButton.prototype.select=function(){this.over=this.selected=!0;this.tl.play()};IOSButton.prototype.deselect=function(){this.selected=!1;this.tl.reverse();this.over=!1};IOSButton.prototype.onMouseClick=function(){HIGH?window.open(this.url):window.open(this.url,"_self")};IOSButton.prototype.onMouseOver=function(){this.selected||(this.tl.play(),this.over=!0)};
IOSButton.prototype.onReachTop=function(){this.over?this.sprite.setTexture(this.yellow):this.sprite.setTexture(this.white)};IOSButton.prototype.onMouseOut=function(){this.selected||(this.tl.reverse(),this.over=!1)};
IOSButton.prototype.updateTransform=function(){PIXI.DisplayObjectContainer.prototype.updateTransform.call(this);this.div.style.display=this.visible?"block":"none";this.div.style.width="187px";this.div.style.height="98px";var a=this.worldTransform,a="matrix("+a[0]+", "+a[3]+","+a[1]+","+a[4]+","+(a[2]-93.5+offset)+","+(a[5]-49)+")";this.div.style["-webkit-transform"]=a;this.div.style.transform=a};